apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcommerce
  template:
    metadata:
      labels:
        app: webcommerce
    spec:
      initContainers:
        - name: init-index
          image: "registry.gitlab.com/lachuernet/devops_webservice/webcommerce:{{ .Values.tagWeb }}"
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /var/www/html
              cp /index.html /var/www/html/index.html
          volumeMounts:
            - name: wordpress-volume
              mountPath: /var/www/html
      containers:
        - name: wordpress
          image: {{ .Values.image | default .Values.wordpress.image }}
          env:
            - name: WORDPRESS_DB_HOST
              value: "{{ .Values.wordpress.dbHost }}"
            - name: WORDPRESS_DB_USER
              value: "{{ .Values.wordpress.dbUser }}"
            - name: WORDPRESS_DB_PASSWORD
              value: "{{ .Values.wordpress.dbPassword }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-volume
      volumes:
        - name: wordpress-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-wordpress-pvc
      imagePullSecrets:
        {{- if .Values.wordpress.imagePullSecret }}
        - name: {{ .Values.wordpress.imagePullSecret }}
        {{- end }}