apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  #namespace: projet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wordpress.storage }}
