apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webcommerce
  #namespace: projet
spec:
  type: NodePort
  selector:
    app: webcommerce
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 30080
