#imagePullSecret: gitlab-registry-secret
tagWeb:da0b03e609a709e54834b5a6d1490d0d49f7cd30


webcommerce:
  wordpress:
    #image: salim2025/webcommerce:v1
    image: registry.gitlab.com/lachuernet/devops_webservice/webcommerce:{{ .Values.tagWeb:da0b03e609a709e54834b5a6d1490d0d49f7cd30
    imagePullSecret: gitlab-registry-secret
    storage: 5Gi
mysqlcommerce:
  mysql:
    image: registry.gitlab.com/lachuernet/devops_webservice/mysqlcommerce:{{ .Values.tagWeb:da0b03e609a709e54834b5a6d1490d0d49f7cd30
    imagePullSecret: gitlab-registry-secret
    storage: 5Gi